%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

host: "127.0.0.1"

# Read ports
lidar.port: "4000"
camera.port: "4001"
imu.port: "4002"

# Write ports
det2d.port: "4003"
det3d.port: "4004"